
# test_mock_api.py
#
# THIS CODE WAS AUTOMATICALLY GENERATED BY generate_tests.py.
#
import requests
import pytest

# --- Configuration ---
BASE_URL = "http://127.0.0.1:8000/projects"
AUTH_HEADERS = {"X-API-KEY": "MOCK_TOKEN_123"}

# Test data from the generated 'testdata.json'
TEST_CREATE_PAYLOAD = {
        "key": "PRO-1",
        "name": "Project 1",
        "fields": {
            "summary": "Summary of issue 1",
            "description": "Description of issue 1",
            "status": "Open",
            "assignee": "John Doe",
            "issuetype": "Bug",
            "project": "PRO-1"
        }
    }
TEST_UPDATE_PAYLOAD = {
        "key": "PRO-2",
        "name": "Project 2",
        "fields": {
            "summary": "Summary of issue 2",
            "description": "Description of issue 2",
            "status": "Open",
            "assignee": "Jane Doe",
            "issuetype": "Feature",
            "project": "PRO-2"
        }
    }


# Global variable to store the created ID for CRUD tests
global_id = None 

# --- Pytest Fixture (Setup) ---
@pytest.fixture(scope="module", autouse=True)
def setup_teardown():
    global global_id
    
    # 1. SETUP: Create an object for later testing
    print("\n--- SETUP: Creating test object for CRUD tests ---")
    try:
        # POST request to create the resource
        response = requests.post(BASE_URL, headers=AUTH_HEADERS, json=TEST_CREATE_PAYLOAD, timeout=5)
        response.raise_for_status()
        global_id = response.json().get('id')
        assert global_id is not None
        print(f"    -> Object successfully created with ID: {global_id}")
    except Exception as e:
        print(f"    -> SETUP FAILED: {e}")
        pytest.fail(f"Setup object could not be created: {e}")
        
    yield 

    # 2. TEARDOWN: Clean up after tests 
    if global_id:
        print("\n--- TEARDOWN: Deleting test object ---")
        try:
            # DELETE request for cleanup
            response = requests.delete(f"{BASE_URL}/{global_id}", headers=AUTH_HEADERS, timeout=5)
            # Accept 204 or 404
            if response.status_code not in [204, 404]:
                response.raise_for_status() 
            print("    -> Cleanup successful.")
        except Exception as e:
            print(f"    -> WARNING: Cleanup failed: {e}")
            global_id = None


# --- 1. Security/Auth Test ---
def test_post_creation_requires_auth():
    # Checks if POST requests without API key are rejected (401).
    response = requests.post(BASE_URL, json=TEST_CREATE_PAYLOAD, timeout=5)
    assert response.status_code == 401
    assert response.json().get("detail", "Detail field missing").startswith("Authorization required")

# --- 2. Read All Test ---
def test_get_all_success():
    # Checks if GET / is successful and returns a list.
    response = requests.get(BASE_URL, timeout=5)
    assert response.status_code == 200
    assert isinstance(response.json(), list)
    assert len(response.json()) > 0

# --- 3. Read One Test ---
def test_get_one_success():
    # Checks if GET /{id} returns the correct object.
    
    if global_id is None:
        pytest.skip("Setup failed: global_id not available.")

    response = requests.get(f"{BASE_URL}/{global_id}", timeout=5)
    assert response.status_code == 200
    assert response.json().get('id') == global_id

# --- 4. Update Test ---
def test_put_update_success():
    # Checks if PUT /{id} successfully updates the object.
    global global_id
    
    if global_id is None:
        pytest.skip("Setup failed: global_id not available.")
        
    update_data = TEST_UPDATE_PAYLOAD.copy() 
    update_data['id'] = global_id 
    
    # Send PUT request
    response = requests.put(f"{BASE_URL}/{global_id}", headers=AUTH_HEADERS, json=update_data, timeout=5)
    assert response.status_code == 200
    
    # Check if the response contains the updated object with the correct ID
    assert response.json().get('id') == global_id
    
    # Check updated value
    first_update_key = next(iter(TEST_UPDATE_PAYLOAD.keys()), None)
    if first_update_key:
        assert response.json().get(first_update_key) == TEST_UPDATE_PAYLOAD.get(first_update_key)


# --- 5. Delete Test ---
def test_delete_success():
    # Checks if DELETE /{id} is successful (204) and the object no longer exists afterwards (404).
    global global_id
    
    # 1. Temporarily create a new object
    try:
        response_post = requests.post(BASE_URL, headers=AUTH_HEADERS, json=TEST_CREATE_PAYLOAD, timeout=5)
        response_post.raise_for_status()
        temp_id = response_post.json().get('id')
        if temp_id is None:
             pytest.fail("Could not create a temporary object for the DELETE test.")
    except Exception as e:
        pytest.fail(f"Error creating temp object: {e}")


    # 2. Send DELETE request
    response_delete = requests.delete(f"{BASE_URL}/{temp_id}", headers=AUTH_HEADERS, timeout=5)
    assert response_delete.status_code == 204

    # 3. Check if the object is truly deleted
    response_check = requests.get(f"{BASE_URL}/{temp_id}", timeout=5)
    assert response_check.status_code == 404
    
    # The global ID for the fixture remains untouched.
